[package]
name = "alloy-rpc"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
alloy-core = { path = "../alloy-core" }
prost.workspace = true
serde.workspace = true
