[package]
name = "alloy-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
jsonwebtoken.workspace = true
serde.workspace = true
thiserror.workspace = true
